services:
  api:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=production
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASS=${ADMIN_PASS}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./downloads:/app/downloads
      - ./data.json:/app/data.json
    restart: always
